- name: Install package repository
  ansible.builtin.include_tasks: repository.yml

- name: Install Consul apt preferences
  ansible.builtin.template:
    src: etc/apt/preferences.d/99-ansible-consul.j2
    dest: /etc/apt/preferences.d/99-ansible-consul
    mode: "0644"

- name: Install Consul package
  ansible.builtin.apt:
    name: "{{ consul_package }}"
    state: "{{ consul_package_state }}"
    policy_rc_d: "{{ consul_package_policy_rc_d }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Mask Consul service installed by package
  ansible.builtin.systemd:
    name: consul
    enabled: false
    state: stopped
    masked: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create Consul script checks directory
  ansible.builtin.file:
    path: "{{ consul_script_checks_directory }}"
    owner: "{{ consul_script_checks_directory_owner | d(omit) }}"
    group: "{{ consul_script_checks_directory_group | d(omit) }}"
    mode: "{{ consul_script_checks_directory_mode | d(omit) }}"
    state: directory

- name: Combine Consul script check variables
  ansible.builtin.set_fact:
    _consul_script_checks: >-
      {{
        [
          consul_script_checks,
          consul_group_script_checks,
          consul_host_script_checks
        ] | flatten
      }}

- name: Install Consul script checks
  ansible.builtin.copy:
    src: "{{ item.src | d(omit) }}"
    content: "{{ item.content | d(omit) }}"
    dest: "{{ consul_script_checks_directory }}/{{ item.name }}"
    mode: "{{ item.mode | d('0755') }}"
    owner: "{{ item.owner | d(omit) }}"
    group: "{{ item.group | d(omit) }}"
    force: "{{ item.force | d(omit) }}"
  loop: "{{ _consul_script_checks }}"
  when:
    - item.name is defined
    - item.src is defined or item.content is defined
    - not item.skipped_when | d(false) | bool

- name: Download and install Consul script checks
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ consul_script_checks_directory }}/{{ item.name }}"
    mode: "{{ item.mode | d('0755') }}"
    owner: "{{ item.owner | d(omit) }}"
    group: "{{ item.group | d(omit) }}"
    force: "{{ item.force | d(omit) }}"
    checksum: "{{ item.checksum | d(omit) }}"
    username: "{{ item.username | d(omit) }}"
    password: "{{ item.password | d(omit) }}"
    validate_certs: "{{ item.validate_certs | d(omit) }}"
  loop: "{{ _consul_script_checks }}"
  when:
    - item.name is defined
    - item.url is defined
    - not item.skipped_when | d(false) | bool

- name: Install and configure Consul server
  ansible.builtin.include_tasks: server.yml
  when: consul_server | bool

- name: Install and configure Consul client
  ansible.builtin.include_tasks: client.yml
  when: consul_client | bool

- name: Flush handlers to ensure Consul is restarted
  ansible.builtin.meta: flush_handlers
  when: consul_flush_handlers | bool
