- name: Install package repository
  include_tasks: repository.yml

- name: Install Consul package
  apt:
    name: >-
      {{
        'consul={}'.format(consul_package_version) if (consul_package_version | d())
        else 'consul'
      }}
    state: "{{ consul_package_state }}"
    policy_rc_d: "{{ consul_package_policy_rc_d }}"

- name: Set Consul package dpkg selection state
  dpkg_selections:
    name: consul
    selection: "{{ consul_package_dpkg_selection }}"
  when: consul_package_dpkg_selection | d()

- name: Mask Consul service installed by package
  systemd:
    name: consul
    enabled: false
    state: stopped
    masked: true

- name: Install and configure Consul server
  include_tasks: server.yml
  when: consul_server

- name: Install and configure Consul client
  include_tasks: client.yml
  when: consul_client

- name: Flush handlers to ensure Consul is restarted
  meta: flush_handlers
  when: consul_flush_handlers
