---
- name: Create Consul server data directory
  ansible.builtin.file:
    path: "{{ consul_server_data_directory }}"
    owner: "{{ consul_server_data_directory_owner }}"
    group: "{{ consul_server_data_directory_group }}"
    mode: "{{ consul_server_data_directory_mode }}"
    state: directory

- name: Install Consul server SystemD service
  ansible.builtin.template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{ consul_server_service_name }}.service
    mode: "0644"
  notify:
    - reload systemd
    - restart consul server
  vars:
    service_config: >-
      {{
        consul_server_service_configuration | combine(
          consul_server_group_service_configuration,
          consul_server_host_service_configuration,
          list_merge=consul_service_configuration_list_merge,
          recursive=consul_service_configuration_recursive_merge
        )
      }}

- name: Install Consul server environment file
  ansible.builtin.template:
    src: consul.env.j2
    dest: "{{ consul_server_environment_file }}"
    owner: "{{ consul_server_environment_file_owner }}"
    group: "{{ consul_server_environment_file_group }}"
    mode: "{{ consul_server_environment_file_mode }}"
  notify: restart consul server
  vars:
    _consul_environment: >-
      {{
        consul_server_environment | combine(
          consul_server_group_environment,
          consul_server_host_environment
        )
      }}

- name: Install Consul server configuration
  ansible.builtin.template:
    src: consul.json.j2
    dest: "{{ consul_server_configuration_file }}"
    owner: "{{ consul_server_configuration_file_owner }}"
    group: "{{ consul_server_configuration_file_group }}"
    mode: "{{ consul_server_configuration_file_mode }}"
  notify: restart consul server
  vars:
    _consul_configuration: >-
      {{
        consul_server_configuration | combine(
          consul_server_group_configuration,
          consul_server_host_configuration,
          list_merge=consul_configuration_list_merge,
          recursive=consul_configuration_recursive_merge
        )
      }}

- name: Enable and start Consul server service
  ansible.builtin.service:
    name: "{{ consul_server_service_name }}"
    state: "{{ consul_server_service_state }}"
    enabled: "{{ consul_server_service_enabled }}"
  ignore_errors: "{{ ansible_check_mode }}"
