---
- name: Reload SystemD
  listen: reload systemd
  systemd:
    daemon_reload: true

- name: Restart Consul
  listen: restart consul
  service:
    name: consul
    state: "{{ consul_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
