---
- name: Reload SystemD
  listen: reload systemd
  systemd:
    daemon_reload: true

- name: Restart Consul client
  listen: restart consul client
  service:
    name: "{{ consul_client_service_name }}"
    state: "{{ consul_client_restart_handler_state }}"
  when: consul_client_service_enabled
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart Consul server
  listen: restart consul server
  service:
    name: "{{ consul_server_service_name }}"
    state: "{{ consul_server_restart_handler_state }}"
  when: consul_server_service_enabled
  ignore_errors: "{{ ansible_check_mode }}"
