consul_server: false

consul_package_version: 1.15.1-1
consul_package_dpkg_selection: hold

consul_client_host_configuration:
  encrypt: "{{ consul_encryption_key }}"
  retry_join: >-
    {{
      groups['consul_servers'] |
      product(['8301']) |
      map('join', ':')
    }}
