---
consul_encryption_key: "2BUGpqtEoh/Gy+AztZpX+d5Zx2ZYdLHeXcLYwIPTGi4="

consul_server_group_configuration:
  bind_addr: 0.0.0.0
  encrypt: "{{ consul_encryption_key }}"
  retry_join: "{{ groups['consul_servers'] | difference([inventory_hostname]) }}"
