---
consul_client: true

consul_client_host_configuration:
  encrypt: "{{ consul_encryption_key }}"
  retry_join: >-
    {{
      groups['consul_servers'] |
      product(['8301']) |
      map('join', ':')
    }}
